apiVersion: v2
name: polygon-parts-worker
description: A Helm chart for polygon-parts-worker
type: application
version: 2.1.2
appVersion: 2.1.2
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
