apiVersion: v2
name: polygon-parts-worker
description: A Helm chart for polygon-parts-worker
type: application
version: 2.0.0-alpha.1
appVersion: 2.0.0-alpha.1
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
