name: pull_request

on: [pull_request]

jobs:
  pull_request:
    uses: MapColonies/shared-workflows/.github/workflows/pull_request.yaml@v4
    secrets: inherit
    with:
      enableOpenApiCheck: false
      preInstallCommands: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev
